POST http://localhost:3004/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNjM2NGZiOGIwMGFmNjFiNjg0N2NlNyIsImlhdCI6MTY2NzQ1OTA2NCwiZXhwIjoxNjY3NTQ1NDY0fQ.edShn5SeCwzgvZpih2cGTQ5GT3Nmzf6NJhtfGCqSwB4

{
"name": "Bush Furniture Salinas Cape Cod Grey 6-cube Organizer",
"description":
    "Make organization a charming task with the serene, sophisticated lines and subdued, stormy color of this cube organizer.",
"price": 148.5,
"imagePath":
    "https://ak1.ostkcdn.com/images/products/is/images/direct/54ce209df375b81b1cdc594f405a6520fbaf139e/The-Gray-Barn-Lowbridge-Cape-Cod-Grey-6-cube-Organizer.jpg?impolicy=medium"
}

###
POST http://localhost:3004/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNjM2NGZiOGIwMGFmNjFiNjg0N2NlNyIsImlhdCI6MTY2NzQ1OTA2NCwiZXhwIjoxNjY3NTQ1NDY0fQ.edShn5SeCwzgvZpih2cGTQ5GT3Nmzf6NJhtfGCqSwB4

{
"name": "Peninah Faux Rubberwood Writing Desk by Christopher Knight Home",
"description":
    "Have an enjoyable time working on this Peninah writing desk. A faux-wood overlay adds classic charm to this sturdy rubberwood desk, which has a minimalist design that fits compact spaces and lends mid-century flair to your writing corner. Store your pens, papers, folders, and laptop in the handy large drawer.",
"price": 214.64,
"imagePath":
    "https://ak1.ostkcdn.com/images/products/is/images/direct/a5e199f5f6f242878504d092ec9fc8ec330abd58/Peninah-Mid-Century-Faux-Rubberwood-Writing-Desk-by-Christopher-Knight-Home.jpg?impolicy=medium"
}

###
POST http://localhost:3004/api/products
Content-Type: application/json

{
    "name": "Loadout 48 Gaming Desk",
    "description": "Working has not been so much fun but when you have a desk like this you won\"t mind working at this attractive desk. Designed in a mid-century modern style, it features shaped tapered legs, square handle drawer pull, and a walnut finish.",
    "price": 153.49,
    "imagePath": "https://ak1.ostkcdn.com/images/products/is/images/direct/d6cb0648abca74c10434a090ad1e235079314e90/Loadout-48%22-Gaming-Desk.jpg?impolicy=medium"
}