DELETE http://localhost:3004/api/products/6363f35119cccfd6c1010168
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNjEwNmNhYWVhMTZhYTAzMWZmYzAxMiIsImlhdCI6MTY2NzQ0MzUxNywiZXhwIjoxNjY3NDQ3MTE3fQ.2C6513O0uj70eEUdygwLD5kuol74JCIf0dCWruf7Jdo
