POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "123"
}

###
POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "shopper",
    "password": "shopper123"
}