GET http://localhost:3004/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNjNjMjU4NDVkNDdhNmUwNzM5NjI1OSIsImlhdCI6MTY2NzUwNDM3MiwiZXhwIjoxNjY3NTkwNzcyfQ.CMpaMSWlBXQjYj9XmprVfDPNx9V-Lr3eG89c4rG5O5M

###
GET http://localhost:3004/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob3BwZXIiLCJpZCI6IjYzNjM2ZTRiNDBlYTI2ZWFkMGRmMTg2MiIsImlhdCI6MTY2NzQ2MDg1NCwiZXhwIjoxNjY3NTQ3MjU0fQ.ZEnCdSELXmGUH4h7Fo7Mb5XIZScRomqmTUiqQ-P7j-8
